/* eslint-disable */
/** Auto-generated by scripts/generate-world-countries.mjs — do not edit manually. */

export type WorldCountryRow = {
  name: string;
  isoCode: string;
  phoneCode: string;
};

export const WORLD_COUNTRIES: WorldCountryRow[] = [
  {
    "name": "Afghanistan",
    "isoCode": "AF",
    "phoneCode": "+93"
  },
  {
    "name": "Aland Islands",
    "isoCode": "AX",
    "phoneCode": "+35818"
  },
  {
    "name": "Albania",
    "isoCode": "AL",
    "phoneCode": "+355"
  },
  {
    "name": "Algeria",
    "isoCode": "DZ",
    "phoneCode": "+213"
  },
  {
    "name": "American Samoa",
    "isoCode": "AS",
    "phoneCode": "+1684"
  },
  {
    "name": "Andorra",
    "isoCode": "AD",
    "phoneCode": "+376"
  },
  {
    "name": "Angola",
    "isoCode": "AO",
    "phoneCode": "+244"
  },
  {
    "name": "Anguilla",
    "isoCode": "AI",
    "phoneCode": "+1264"
  },
  {
    "name": "Antarctica",
    "isoCode": "AQ",
    "phoneCode": "+672"
  },
  {
    "name": "Antigua And Barbuda",
    "isoCode": "AG",
    "phoneCode": "+1268"
  },
  {
    "name": "Argentina",
    "isoCode": "AR",
    "phoneCode": "+54"
  },
  {
    "name": "Armenia",
    "isoCode": "AM",
    "phoneCode": "+374"
  },
  {
    "name": "Aruba",
    "isoCode": "AW",
    "phoneCode": "+297"
  },
  {
    "name": "Australia",
    "isoCode": "AU",
    "phoneCode": "+61"
  },
  {
    "name": "Austria",
    "isoCode": "AT",
    "phoneCode": "+43"
  },
  {
    "name": "Azerbaijan",
    "isoCode": "AZ",
    "phoneCode": "+994"
  },
  {
    "name": "Bahrain",
    "isoCode": "BH",
    "phoneCode": "+973"
  },
  {
    "name": "Bangladesh",
    "isoCode": "BD",
    "phoneCode": "+880"
  },
  {
    "name": "Barbados",
    "isoCode": "BB",
    "phoneCode": "+1246"
  },
  {
    "name": "Belarus",
    "isoCode": "BY",
    "phoneCode": "+375"
  },
  {
    "name": "Belgium",
    "isoCode": "BE",
    "phoneCode": "+32"
  },
  {
    "name": "Belize",
    "isoCode": "BZ",
    "phoneCode": "+501"
  },
  {
    "name": "Benin",
    "isoCode": "BJ",
    "phoneCode": "+229"
  },
  {
    "name": "Bermuda",
    "isoCode": "BM",
    "phoneCode": "+1441"
  },
  {
    "name": "Bhutan",
    "isoCode": "BT",
    "phoneCode": "+975"
  },
  {
    "name": "Bolivia",
    "isoCode": "BO",
    "phoneCode": "+591"
  },
  {
    "name": "Bonaire, Sint Eustatius and Saba",
    "isoCode": "BQ",
    "phoneCode": "+599"
  },
  {
    "name": "Bosnia and Herzegovina",
    "isoCode": "BA",
    "phoneCode": "+387"
  },
  {
    "name": "Botswana",
    "isoCode": "BW",
    "phoneCode": "+267"
  },
  {
    "name": "Bouvet Island",
    "isoCode": "BV",
    "phoneCode": "+0055"
  },
  {
    "name": "Brazil",
    "isoCode": "BR",
    "phoneCode": "+55"
  },
  {
    "name": "British Indian Ocean Territory",
    "isoCode": "IO",
    "phoneCode": "+246"
  },
  {
    "name": "Brunei",
    "isoCode": "BN",
    "phoneCode": "+673"
  },
  {
    "name": "Bulgaria",
    "isoCode": "BG",
    "phoneCode": "+359"
  },
  {
    "name": "Burkina Faso",
    "isoCode": "BF",
    "phoneCode": "+226"
  },
  {
    "name": "Burundi",
    "isoCode": "BI",
    "phoneCode": "+257"
  },
  {
    "name": "Cambodia",
    "isoCode": "KH",
    "phoneCode": "+855"
  },
  {
    "name": "Cameroon",
    "isoCode": "CM",
    "phoneCode": "+237"
  },
  {
    "name": "Canada",
    "isoCode": "CA",
    "phoneCode": "+1"
  },
  {
    "name": "Cape Verde",
    "isoCode": "CV",
    "phoneCode": "+238"
  },
  {
    "name": "Cayman Islands",
    "isoCode": "KY",
    "phoneCode": "+1345"
  },
  {
    "name": "Central African Republic",
    "isoCode": "CF",
    "phoneCode": "+236"
  },
  {
    "name": "Chad",
    "isoCode": "TD",
    "phoneCode": "+235"
  },
  {
    "name": "Chile",
    "isoCode": "CL",
    "phoneCode": "+56"
  },
  {
    "name": "China",
    "isoCode": "CN",
    "phoneCode": "+86"
  },
  {
    "name": "Christmas Island",
    "isoCode": "CX",
    "phoneCode": "+61"
  },
  {
    "name": "Cocos (Keeling) Islands",
    "isoCode": "CC",
    "phoneCode": "+61"
  },
  {
    "name": "Colombia",
    "isoCode": "CO",
    "phoneCode": "+57"
  },
  {
    "name": "Comoros",
    "isoCode": "KM",
    "phoneCode": "+269"
  },
  {
    "name": "Congo",
    "isoCode": "CG",
    "phoneCode": "+242"
  },
  {
    "name": "Cook Islands",
    "isoCode": "CK",
    "phoneCode": "+682"
  },
  {
    "name": "Costa Rica",
    "isoCode": "CR",
    "phoneCode": "+506"
  },
  {
    "name": "Cote D'Ivoire (Ivory Coast)",
    "isoCode": "CI",
    "phoneCode": "+225"
  },
  {
    "name": "Croatia",
    "isoCode": "HR",
    "phoneCode": "+385"
  },
  {
    "name": "Cuba",
    "isoCode": "CU",
    "phoneCode": "+53"
  },
  {
    "name": "Curaçao",
    "isoCode": "CW",
    "phoneCode": "+599"
  },
  {
    "name": "Cyprus",
    "isoCode": "CY",
    "phoneCode": "+357"
  },
  {
    "name": "Czech Republic",
    "isoCode": "CZ",
    "phoneCode": "+420"
  },
  {
    "name": "Democratic Republic of the Congo",
    "isoCode": "CD",
    "phoneCode": "+243"
  },
  {
    "name": "Denmark",
    "isoCode": "DK",
    "phoneCode": "+45"
  },
  {
    "name": "Djibouti",
    "isoCode": "DJ",
    "phoneCode": "+253"
  },
  {
    "name": "Dominica",
    "isoCode": "DM",
    "phoneCode": "+1767"
  },
  {
    "name": "Dominican Republic",
    "isoCode": "DO",
    "phoneCode": "+18091829"
  },
  {
    "name": "East Timor",
    "isoCode": "TL",
    "phoneCode": "+670"
  },
  {
    "name": "Ecuador",
    "isoCode": "EC",
    "phoneCode": "+593"
  },
  {
    "name": "Egypt",
    "isoCode": "EG",
    "phoneCode": "+20"
  },
  {
    "name": "El Salvador",
    "isoCode": "SV",
    "phoneCode": "+503"
  },
  {
    "name": "Equatorial Guinea",
    "isoCode": "GQ",
    "phoneCode": "+240"
  },
  {
    "name": "Eritrea",
    "isoCode": "ER",
    "phoneCode": "+291"
  },
  {
    "name": "Estonia",
    "isoCode": "EE",
    "phoneCode": "+372"
  },
  {
    "name": "Ethiopia",
    "isoCode": "ET",
    "phoneCode": "+251"
  },
  {
    "name": "Falkland Islands",
    "isoCode": "FK",
    "phoneCode": "+500"
  },
  {
    "name": "Faroe Islands",
    "isoCode": "FO",
    "phoneCode": "+298"
  },
  {
    "name": "Fiji Islands",
    "isoCode": "FJ",
    "phoneCode": "+679"
  },
  {
    "name": "Finland",
    "isoCode": "FI",
    "phoneCode": "+358"
  },
  {
    "name": "France",
    "isoCode": "FR",
    "phoneCode": "+33"
  },
  {
    "name": "French Guiana",
    "isoCode": "GF",
    "phoneCode": "+594"
  },
  {
    "name": "French Polynesia",
    "isoCode": "PF",
    "phoneCode": "+689"
  },
  {
    "name": "French Southern Territories",
    "isoCode": "TF",
    "phoneCode": "+262"
  },
  {
    "name": "Gabon",
    "isoCode": "GA",
    "phoneCode": "+241"
  },
  {
    "name": "Georgia",
    "isoCode": "GE",
    "phoneCode": "+995"
  },
  {
    "name": "Germany",
    "isoCode": "DE",
    "phoneCode": "+49"
  },
  {
    "name": "Ghana",
    "isoCode": "GH",
    "phoneCode": "+233"
  },
  {
    "name": "Gibraltar",
    "isoCode": "GI",
    "phoneCode": "+350"
  },
  {
    "name": "Greece",
    "isoCode": "GR",
    "phoneCode": "+30"
  },
  {
    "name": "Greenland",
    "isoCode": "GL",
    "phoneCode": "+299"
  },
  {
    "name": "Grenada",
    "isoCode": "GD",
    "phoneCode": "+1473"
  },
  {
    "name": "Guadeloupe",
    "isoCode": "GP",
    "phoneCode": "+590"
  },
  {
    "name": "Guam",
    "isoCode": "GU",
    "phoneCode": "+1671"
  },
  {
    "name": "Guatemala",
    "isoCode": "GT",
    "phoneCode": "+502"
  },
  {
    "name": "Guernsey and Alderney",
    "isoCode": "GG",
    "phoneCode": "+441481"
  },
  {
    "name": "Guinea",
    "isoCode": "GN",
    "phoneCode": "+224"
  },
  {
    "name": "Guinea-Bissau",
    "isoCode": "GW",
    "phoneCode": "+245"
  },
  {
    "name": "Guyana",
    "isoCode": "GY",
    "phoneCode": "+592"
  },
  {
    "name": "Haiti",
    "isoCode": "HT",
    "phoneCode": "+509"
  },
  {
    "name": "Heard Island and McDonald Islands",
    "isoCode": "HM",
    "phoneCode": "+672"
  },
  {
    "name": "Honduras",
    "isoCode": "HN",
    "phoneCode": "+504"
  },
  {
    "name": "Hong Kong S.A.R.",
    "isoCode": "HK",
    "phoneCode": "+852"
  },
  {
    "name": "Hungary",
    "isoCode": "HU",
    "phoneCode": "+36"
  },
  {
    "name": "Iceland",
    "isoCode": "IS",
    "phoneCode": "+354"
  },
  {
    "name": "India",
    "isoCode": "IN",
    "phoneCode": "+91"
  },
  {
    "name": "Indonesia",
    "isoCode": "ID",
    "phoneCode": "+62"
  },
  {
    "name": "Iran",
    "isoCode": "IR",
    "phoneCode": "+98"
  },
  {
    "name": "Iraq",
    "isoCode": "IQ",
    "phoneCode": "+964"
  },
  {
    "name": "Ireland",
    "isoCode": "IE",
    "phoneCode": "+353"
  },
  {
    "name": "Israel",
    "isoCode": "IL",
    "phoneCode": "+972"
  },
  {
    "name": "Italy",
    "isoCode": "IT",
    "phoneCode": "+39"
  },
  {
    "name": "Jamaica",
    "isoCode": "JM",
    "phoneCode": "+1876"
  },
  {
    "name": "Japan",
    "isoCode": "JP",
    "phoneCode": "+81"
  },
  {
    "name": "Jersey",
    "isoCode": "JE",
    "phoneCode": "+441534"
  },
  {
    "name": "Jordan",
    "isoCode": "JO",
    "phoneCode": "+962"
  },
  {
    "name": "Kazakhstan",
    "isoCode": "KZ",
    "phoneCode": "+7"
  },
  {
    "name": "Kenya",
    "isoCode": "KE",
    "phoneCode": "+254"
  },
  {
    "name": "Kiribati",
    "isoCode": "KI",
    "phoneCode": "+686"
  },
  {
    "name": "Kosovo",
    "isoCode": "XK",
    "phoneCode": "+383"
  },
  {
    "name": "Kuwait",
    "isoCode": "KW",
    "phoneCode": "+965"
  },
  {
    "name": "Kyrgyzstan",
    "isoCode": "KG",
    "phoneCode": "+996"
  },
  {
    "name": "Laos",
    "isoCode": "LA",
    "phoneCode": "+856"
  },
  {
    "name": "Latvia",
    "isoCode": "LV",
    "phoneCode": "+371"
  },
  {
    "name": "Lebanon",
    "isoCode": "LB",
    "phoneCode": "+961"
  },
  {
    "name": "Lesotho",
    "isoCode": "LS",
    "phoneCode": "+266"
  },
  {
    "name": "Liberia",
    "isoCode": "LR",
    "phoneCode": "+231"
  },
  {
    "name": "Libya",
    "isoCode": "LY",
    "phoneCode": "+218"
  },
  {
    "name": "Liechtenstein",
    "isoCode": "LI",
    "phoneCode": "+423"
  },
  {
    "name": "Lithuania",
    "isoCode": "LT",
    "phoneCode": "+370"
  },
  {
    "name": "Luxembourg",
    "isoCode": "LU",
    "phoneCode": "+352"
  },
  {
    "name": "Macau S.A.R.",
    "isoCode": "MO",
    "phoneCode": "+853"
  },
  {
    "name": "Macedonia",
    "isoCode": "MK",
    "phoneCode": "+389"
  },
  {
    "name": "Madagascar",
    "isoCode": "MG",
    "phoneCode": "+261"
  },
  {
    "name": "Malawi",
    "isoCode": "MW",
    "phoneCode": "+265"
  },
  {
    "name": "Malaysia",
    "isoCode": "MY",
    "phoneCode": "+60"
  },
  {
    "name": "Maldives",
    "isoCode": "MV",
    "phoneCode": "+960"
  },
  {
    "name": "Mali",
    "isoCode": "ML",
    "phoneCode": "+223"
  },
  {
    "name": "Malta",
    "isoCode": "MT",
    "phoneCode": "+356"
  },
  {
    "name": "Man (Isle of)",
    "isoCode": "IM",
    "phoneCode": "+441624"
  },
  {
    "name": "Marshall Islands",
    "isoCode": "MH",
    "phoneCode": "+692"
  },
  {
    "name": "Martinique",
    "isoCode": "MQ",
    "phoneCode": "+596"
  },
  {
    "name": "Mauritania",
    "isoCode": "MR",
    "phoneCode": "+222"
  },
  {
    "name": "Mauritius",
    "isoCode": "MU",
    "phoneCode": "+230"
  },
  {
    "name": "Mayotte",
    "isoCode": "YT",
    "phoneCode": "+262"
  },
  {
    "name": "Mexico",
    "isoCode": "MX",
    "phoneCode": "+52"
  },
  {
    "name": "Micronesia",
    "isoCode": "FM",
    "phoneCode": "+691"
  },
  {
    "name": "Moldova",
    "isoCode": "MD",
    "phoneCode": "+373"
  },
  {
    "name": "Monaco",
    "isoCode": "MC",
    "phoneCode": "+377"
  },
  {
    "name": "Mongolia",
    "isoCode": "MN",
    "phoneCode": "+976"
  },
  {
    "name": "Montenegro",
    "isoCode": "ME",
    "phoneCode": "+382"
  },
  {
    "name": "Montserrat",
    "isoCode": "MS",
    "phoneCode": "+1664"
  },
  {
    "name": "Morocco",
    "isoCode": "MA",
    "phoneCode": "+212"
  },
  {
    "name": "Mozambique",
    "isoCode": "MZ",
    "phoneCode": "+258"
  },
  {
    "name": "Myanmar",
    "isoCode": "MM",
    "phoneCode": "+95"
  },
  {
    "name": "Namibia",
    "isoCode": "NA",
    "phoneCode": "+264"
  },
  {
    "name": "Nauru",
    "isoCode": "NR",
    "phoneCode": "+674"
  },
  {
    "name": "Nepal",
    "isoCode": "NP",
    "phoneCode": "+977"
  },
  {
    "name": "Netherlands",
    "isoCode": "NL",
    "phoneCode": "+31"
  },
  {
    "name": "New Caledonia",
    "isoCode": "NC",
    "phoneCode": "+687"
  },
  {
    "name": "New Zealand",
    "isoCode": "NZ",
    "phoneCode": "+64"
  },
  {
    "name": "Nicaragua",
    "isoCode": "NI",
    "phoneCode": "+505"
  },
  {
    "name": "Niger",
    "isoCode": "NE",
    "phoneCode": "+227"
  },
  {
    "name": "Nigeria",
    "isoCode": "NG",
    "phoneCode": "+234"
  },
  {
    "name": "Niue",
    "isoCode": "NU",
    "phoneCode": "+683"
  },
  {
    "name": "Norfolk Island",
    "isoCode": "NF",
    "phoneCode": "+672"
  },
  {
    "name": "North Korea",
    "isoCode": "KP",
    "phoneCode": "+850"
  },
  {
    "name": "Northern Mariana Islands",
    "isoCode": "MP",
    "phoneCode": "+1670"
  },
  {
    "name": "Norway",
    "isoCode": "NO",
    "phoneCode": "+47"
  },
  {
    "name": "Oman",
    "isoCode": "OM",
    "phoneCode": "+968"
  },
  {
    "name": "Pakistan",
    "isoCode": "PK",
    "phoneCode": "+92"
  },
  {
    "name": "Palau",
    "isoCode": "PW",
    "phoneCode": "+680"
  },
  {
    "name": "Palestinian Territory Occupied",
    "isoCode": "PS",
    "phoneCode": "+970"
  },
  {
    "name": "Panama",
    "isoCode": "PA",
    "phoneCode": "+507"
  },
  {
    "name": "Papua new Guinea",
    "isoCode": "PG",
    "phoneCode": "+675"
  },
  {
    "name": "Paraguay",
    "isoCode": "PY",
    "phoneCode": "+595"
  },
  {
    "name": "Peru",
    "isoCode": "PE",
    "phoneCode": "+51"
  },
  {
    "name": "Philippines",
    "isoCode": "PH",
    "phoneCode": "+63"
  },
  {
    "name": "Pitcairn Island",
    "isoCode": "PN",
    "phoneCode": "+870"
  },
  {
    "name": "Poland",
    "isoCode": "PL",
    "phoneCode": "+48"
  },
  {
    "name": "Portugal",
    "isoCode": "PT",
    "phoneCode": "+351"
  },
  {
    "name": "Puerto Rico",
    "isoCode": "PR",
    "phoneCode": "+17871939"
  },
  {
    "name": "Qatar",
    "isoCode": "QA",
    "phoneCode": "+974"
  },
  {
    "name": "Reunion",
    "isoCode": "RE",
    "phoneCode": "+262"
  },
  {
    "name": "Romania",
    "isoCode": "RO",
    "phoneCode": "+40"
  },
  {
    "name": "Russia",
    "isoCode": "RU",
    "phoneCode": "+7"
  },
  {
    "name": "Rwanda",
    "isoCode": "RW",
    "phoneCode": "+250"
  },
  {
    "name": "Saint Helena",
    "isoCode": "SH",
    "phoneCode": "+290"
  },
  {
    "name": "Saint Kitts And Nevis",
    "isoCode": "KN",
    "phoneCode": "+1869"
  },
  {
    "name": "Saint Lucia",
    "isoCode": "LC",
    "phoneCode": "+1758"
  },
  {
    "name": "Saint Pierre and Miquelon",
    "isoCode": "PM",
    "phoneCode": "+508"
  },
  {
    "name": "Saint Vincent And The Grenadines",
    "isoCode": "VC",
    "phoneCode": "+1784"
  },
  {
    "name": "Saint-Barthelemy",
    "isoCode": "BL",
    "phoneCode": "+590"
  },
  {
    "name": "Saint-Martin (French part)",
    "isoCode": "MF",
    "phoneCode": "+590"
  },
  {
    "name": "Samoa",
    "isoCode": "WS",
    "phoneCode": "+685"
  },
  {
    "name": "San Marino",
    "isoCode": "SM",
    "phoneCode": "+378"
  },
  {
    "name": "Sao Tome and Principe",
    "isoCode": "ST",
    "phoneCode": "+239"
  },
  {
    "name": "Saudi Arabia",
    "isoCode": "SA",
    "phoneCode": "+966"
  },
  {
    "name": "Senegal",
    "isoCode": "SN",
    "phoneCode": "+221"
  },
  {
    "name": "Serbia",
    "isoCode": "RS",
    "phoneCode": "+381"
  },
  {
    "name": "Seychelles",
    "isoCode": "SC",
    "phoneCode": "+248"
  },
  {
    "name": "Sierra Leone",
    "isoCode": "SL",
    "phoneCode": "+232"
  },
  {
    "name": "Singapore",
    "isoCode": "SG",
    "phoneCode": "+65"
  },
  {
    "name": "Sint Maarten (Dutch part)",
    "isoCode": "SX",
    "phoneCode": "+1721"
  },
  {
    "name": "Slovakia",
    "isoCode": "SK",
    "phoneCode": "+421"
  },
  {
    "name": "Slovenia",
    "isoCode": "SI",
    "phoneCode": "+386"
  },
  {
    "name": "Solomon Islands",
    "isoCode": "SB",
    "phoneCode": "+677"
  },
  {
    "name": "Somalia",
    "isoCode": "SO",
    "phoneCode": "+252"
  },
  {
    "name": "South Africa",
    "isoCode": "ZA",
    "phoneCode": "+27"
  },
  {
    "name": "South Georgia",
    "isoCode": "GS",
    "phoneCode": "+500"
  },
  {
    "name": "South Korea",
    "isoCode": "KR",
    "phoneCode": "+82"
  },
  {
    "name": "South Sudan",
    "isoCode": "SS",
    "phoneCode": "+211"
  },
  {
    "name": "Spain",
    "isoCode": "ES",
    "phoneCode": "+34"
  },
  {
    "name": "Sri Lanka",
    "isoCode": "LK",
    "phoneCode": "+94"
  },
  {
    "name": "Sudan",
    "isoCode": "SD",
    "phoneCode": "+249"
  },
  {
    "name": "Suriname",
    "isoCode": "SR",
    "phoneCode": "+597"
  },
  {
    "name": "Svalbard And Jan Mayen Islands",
    "isoCode": "SJ",
    "phoneCode": "+47"
  },
  {
    "name": "Swaziland",
    "isoCode": "SZ",
    "phoneCode": "+268"
  },
  {
    "name": "Sweden",
    "isoCode": "SE",
    "phoneCode": "+46"
  },
  {
    "name": "Switzerland",
    "isoCode": "CH",
    "phoneCode": "+41"
  },
  {
    "name": "Syria",
    "isoCode": "SY",
    "phoneCode": "+963"
  },
  {
    "name": "Taiwan",
    "isoCode": "TW",
    "phoneCode": "+886"
  },
  {
    "name": "Tajikistan",
    "isoCode": "TJ",
    "phoneCode": "+992"
  },
  {
    "name": "Tanzania",
    "isoCode": "TZ",
    "phoneCode": "+255"
  },
  {
    "name": "Thailand",
    "isoCode": "TH",
    "phoneCode": "+66"
  },
  {
    "name": "The Bahamas",
    "isoCode": "BS",
    "phoneCode": "+1242"
  },
  {
    "name": "The Gambia",
    "isoCode": "GM",
    "phoneCode": "+220"
  },
  {
    "name": "Togo",
    "isoCode": "TG",
    "phoneCode": "+228"
  },
  {
    "name": "Tokelau",
    "isoCode": "TK",
    "phoneCode": "+690"
  },
  {
    "name": "Tonga",
    "isoCode": "TO",
    "phoneCode": "+676"
  },
  {
    "name": "Trinidad And Tobago",
    "isoCode": "TT",
    "phoneCode": "+1868"
  },
  {
    "name": "Tunisia",
    "isoCode": "TN",
    "phoneCode": "+216"
  },
  {
    "name": "Turkey",
    "isoCode": "TR",
    "phoneCode": "+90"
  },
  {
    "name": "Turkmenistan",
    "isoCode": "TM",
    "phoneCode": "+993"
  },
  {
    "name": "Turks And Caicos Islands",
    "isoCode": "TC",
    "phoneCode": "+1649"
  },
  {
    "name": "Tuvalu",
    "isoCode": "TV",
    "phoneCode": "+688"
  },
  {
    "name": "Uganda",
    "isoCode": "UG",
    "phoneCode": "+256"
  },
  {
    "name": "Ukraine",
    "isoCode": "UA",
    "phoneCode": "+380"
  },
  {
    "name": "United Arab Emirates",
    "isoCode": "AE",
    "phoneCode": "+971"
  },
  {
    "name": "United Kingdom",
    "isoCode": "GB",
    "phoneCode": "+44"
  },
  {
    "name": "United States",
    "isoCode": "US",
    "phoneCode": "+1"
  },
  {
    "name": "United States Minor Outlying Islands",
    "isoCode": "UM",
    "phoneCode": "+1"
  },
  {
    "name": "Uruguay",
    "isoCode": "UY",
    "phoneCode": "+598"
  },
  {
    "name": "Uzbekistan",
    "isoCode": "UZ",
    "phoneCode": "+998"
  },
  {
    "name": "Vanuatu",
    "isoCode": "VU",
    "phoneCode": "+678"
  },
  {
    "name": "Vatican City State (Holy See)",
    "isoCode": "VA",
    "phoneCode": "+379"
  },
  {
    "name": "Venezuela",
    "isoCode": "VE",
    "phoneCode": "+58"
  },
  {
    "name": "Vietnam",
    "isoCode": "VN",
    "phoneCode": "+84"
  },
  {
    "name": "Virgin Islands (British)",
    "isoCode": "VG",
    "phoneCode": "+1284"
  },
  {
    "name": "Virgin Islands (US)",
    "isoCode": "VI",
    "phoneCode": "+1340"
  },
  {
    "name": "Wallis And Futuna Islands",
    "isoCode": "WF",
    "phoneCode": "+681"
  },
  {
    "name": "Western Sahara",
    "isoCode": "EH",
    "phoneCode": "+212"
  },
  {
    "name": "Yemen",
    "isoCode": "YE",
    "phoneCode": "+967"
  },
  {
    "name": "Zambia",
    "isoCode": "ZM",
    "phoneCode": "+260"
  },
  {
    "name": "Zimbabwe",
    "isoCode": "ZW",
    "phoneCode": "+263"
  }
] as const;

export const WORLD_COUNTRY_NAMES: string[] = [
  ...WORLD_COUNTRIES.map((c) => c.name),
  "Other",
];

export const WORLD_COUNTRY_BY_NAME = new Map(WORLD_COUNTRIES.map((c) => [c.name, c]));
export const WORLD_COUNTRY_BY_ISO = new Map(WORLD_COUNTRIES.map((c) => [c.isoCode, c]));
