export const LANGUAGE_PROFICIENCY_LEVELS = [
  "Basic",
  "Conversational",
  "Professional",
  "Fluent",
  "Native",
] as const;

export type LanguageProficiency = (typeof LANGUAGE_PROFICIENCY_LEVELS)[number];

export type CandidateLanguageEntry = {
  language: string;
  proficiency: LanguageProficiency | null;
};

export const SKILL_SUGGESTIONS = [
  "JavaScript",
  "TypeScript",
  "Python",
  "Java",
  "C#",
  "C++",
  "Go",
  "Rust",
  "SQL",
  "React",
  "Next.js",
  "Node.js",
  "Vue.js",
  "Angular",
  "HTML",
  "CSS",
  "Tailwind CSS",
  "AWS",
  "Azure",
  "Google Cloud",
  "Docker",
  "Kubernetes",
  "Git",
  "CI/CD",
  "REST APIs",
  "GraphQL",
  "MongoDB",
  "PostgreSQL",
  "MySQL",
  "Redis",
  "Machine Learning",
  "Data Analysis",
  "Excel",
  "Power BI",
  "Tableau",
  "Project Management",
  "Agile",
  "Scrum",
  "Product Management",
  "UI/UX Design",
  "Figma",
  "Communication",
  "Leadership",
  "Customer Service",
  "Sales",
  "Marketing",
  "SEO",
  "Content Writing",
  "Accounting",
  "Finance",
  "HR",
  "Recruitment",
  "Legal Research",
  "Supply Chain",
  "Operations",
  "Quality Assurance",
  "Cybersecurity",
  "DevOps",
  "Mobile Development",
  "iOS",
  "Android",
  "Flutter",
  "React Native",
] as const;

export const CERTIFICATION_SUGGESTIONS = [
  "AWS Certified Solutions Architect",
  "AWS Certified Developer",
  "AWS Certified Cloud Practitioner",
  "Google Cloud Professional Cloud Architect",
  "Microsoft Azure Fundamentals",
  "Microsoft Azure Administrator",
  "CompTIA A+",
  "CompTIA Network+",
  "CompTIA Security+",
  "Cisco CCNA",
  "PMP",
  "PRINCE2 Foundation",
  "Scrum Master (CSM)",
  "Professional Scrum Master (PSM)",
  "ITIL Foundation",
  "CPA",
  "CFA Level I",
  "ACCA",
  "CIPD",
  "SHRM-CP",
  "Six Sigma Green Belt",
  "Six Sigma Black Belt",
  "Google Data Analytics Certificate",
  "Google Project Management Certificate",
  "Meta Front-End Developer Certificate",
  "Certified Kubernetes Administrator (CKA)",
  "HashiCorp Terraform Associate",
  "Salesforce Administrator",
  "TOEFL",
  "IELTS",
  "First Aid / CPR",
] as const;

/** Standardized language names for the multi-select (no free-text). */
export const STANDARD_LANGUAGES = [
  "Afrikaans",
  "Arabic",
  "Bengali",
  "Bulgarian",
  "Burmese",
  "Cantonese",
  "Catalan",
  "Croatian",
  "Czech",
  "Danish",
  "Dutch",
  "English",
  "Estonian",
  "Finnish",
  "French",
  "German",
  "Greek",
  "Gujarati",
  "Hebrew",
  "Hindi",
  "Hungarian",
  "Icelandic",
  "Indonesian",
  "Italian",
  "Japanese",
  "Javanese",
  "Kannada",
  "Korean",
  "Latvian",
  "Lithuanian",
  "Malay",
  "Malayalam",
  "Mandarin Chinese",
  "Marathi",
  "Nepali",
  "Norwegian",
  "Persian",
  "Polish",
  "Portuguese",
  "Punjabi",
  "Romanian",
  "Russian",
  "Serbian",
  "Slovak",
  "Slovenian",
  "Spanish",
  "Swahili",
  "Swedish",
  "Tagalog",
  "Tamil",
  "Telugu",
  "Thai",
  "Turkish",
  "Ukrainian",
  "Urdu",
  "Vietnamese",
] as const;

export const SKILLS_MAX_COUNT = 30;
export const SKILL_MAX_LENGTH = 50;
export const CERTIFICATIONS_MAX_COUNT = 20;
export const CERTIFICATION_MAX_LENGTH = 100;
export const LANGUAGES_MAX_COUNT = 20;
